### ISSUE TITLE
我好激动！！代码在哪里！！

### ISSUE THREAD

**Issue by Rocket1184** [thisforeda/Netease-Music-Spider-Engine#1]
找了这么久终于找到有听歌排行的API了！！
Show me the code Please！！

**Comment by thisforeda** [comment]
暂时没在家，还没完成，快了

**Comment by Rocket1184** [comment]
你这里用的是网页端的API，还是客户端抓包的

**Comment by thisforeda** [comment]
做了一个API，计算请求参数的。
http://api.ozila.cn:9999/listen_rank?uid=0&type=0&limit=20&offset=0&csrf=
把返回结果POST到 http://music.163.com/weapi/v1/play/record?csrf_token=

完成了一多半，上面的是测试的，完成后公开
没看懂你的问题，我是抓包+WIRESHARK一起分析的

**Comment by junbaor** [comment]
哪个语言的 API
